- name: Copy Prometheus configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Restart Prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: Wait for promethues is started or not
  ansible.builtin.wait_for:
    port: 9090
    delay: 10
    timeout: 15

